version: '3'
services:
  service:
    build:
      context: .
      dockerfile: docker/service.Dockerfile
    networks:
      - network
    ports:
      - "55555:55555"
    environment:
      DATABASE_URL: postgres://postgres:p0stgr3s@db:5432/postgres
      RUST_BACKTRACE: 1
      RUST_LOG: test-grpc=debug
  db:
    build:
      context: .
      dockerfile: docker/db.Dockerfile
    restart: always
    networks:
      - network
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr3s
      POSTGRES_DB: postgres

volumes:
  db-data:
    driver: local

networks:
  network: